id = "phpcs"
name = "PHPCS"
version = "0.1.8"
schema_version = 1
authors = ["Mike Bronner <mike@genealabs.com>"]
description = "PHP CodeSniffer Language Server for linting PHP code. We are looking for feedback, especially for Windows and Linux platforms."
repository = "https://github.com/GeneaLabs/zed-phpcs-lsp"

[lib]
kind = "Rust"
version = "0.1.8"

[language_servers.phpcs]
name = "PHPCS"
languages = ["PHP"]
language_ids = { PHP = "php" }
settings = { standard = "PSR12" }
