id = "phpcs-lsp"
name = "PHPCS Language Server"
description = "PHP CodeSniffer Language Server for linting PHP code"
version = "0.1.0"
schema_version = 1
authors = ["Test Author <test@example.com>"]
repository = "https://github.com/your-username/zed-phpcs-lsp"

[lib]
kind = "Rust"
version = "0.6.0"

[language_servers.phpcs-lsp-server]
name = "PHPCS LSP"
languages = ["PHP"]

[language_servers.phpcs-lsp-server.language_ids]
PHP = "php"