id = "phpcs"
name = "PHPCS"
description = "PHP CodeSniffer Language Server for linting PHP code"
version = "0.1.0"
schema_version = 1
authors = ["Mike Bronner <mike.bronner@icloud.com>"]
repository = "https://github.com/GeneaLabs/zed-phpcs-lsp"

[lib]
kind = "Rust"
version = "0.6.0"

[language_servers.phpcs]
name = "PHPCS"
languages = ["PHP"]
language_ids = { PHP = "php" }

# Default settings to enable the language server automatically
[language_servers.phpcs.settings]
standard = "PSR12"
