id = "phpcs"
name = "PHPCS"
description = "PHP CodeSniffer Language Server for linting PHP code"
version = "0.1.3"
schema_version = 1
authors = ["Mike Bronner <mike@genealabs.com>"]
repository = "https://github.com/GeneaLabs/zed-phpcs-lsp"

[lib]
kind = "Rust"
version = "0.1.3"

[language_servers.phpcs]
name = "PHPCS"
languages = ["PHP"]
language_ids = { PHP = "php" }
settings = { standard = "PSR12" }
