id = "phpcs-lsp"
name = "PHPCS"
description = "PHP CodeSniffer Language Server for linting PHP code"
version = "0.1.0"
schema_version = 1
authors = ["Mike Bronner <mike.bronner@icloud.com>"]
repository = "https://github.com/mikebronner/zed-phpcs-lsp"

[lib]
kind = "Rust"
version = "0.6.0"

[language_servers.phpcs-lsp-server]
name = "PHPCS"
languages = ["PHP"]
language_ids = { PHP = "php" }
binary = { path = "bin/phpcs-lsp-server" }
