name: Check PHPCS Updates

on:
  schedule:
    # Check for updates daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if already on latest'
        required: false
        default: 'false'

permissions:
  actions: write

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Get current PHPCS version
      id: current
      run: |
        if [ -f bin/phpcs.phar ]; then
          CURRENT_VERSION=$(php bin/phpcs.phar --version | grep -oP 'version \K[0-9.]+' || echo "0.0.0")
        else
          CURRENT_VERSION="0.0.0"
        fi
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current PHPCS version: $CURRENT_VERSION"

    - name: Get latest PHPCS release
      id: latest
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/squizlabs/PHP_CodeSniffer/releases/latest)
        LATEST_VERSION=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
        LATEST_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "phpcs.phar") | .browser_download_url')
        PHPCBF_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "phpcbf.phar") | .browser_download_url')
        
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "phpcs_url=$LATEST_URL" >> $GITHUB_OUTPUT
        echo "phpcbf_url=$PHPCBF_URL" >> $GITHUB_OUTPUT
        echo "Latest PHPCS version: $LATEST_VERSION"

    - name: Compare versions
      id: compare
      run: |
        CURRENT="${{ steps.current.outputs.version }}"
        LATEST="${{ steps.latest.outputs.version }}"
        FORCE="${{ github.event.inputs.force_update }}"
        
        if [ "$FORCE" = "true" ] || [ "$CURRENT" != "$LATEST" ]; then
          echo "update_needed=true" >> $GITHUB_OUTPUT
          echo "Update needed: $CURRENT -> $LATEST"
        else
          echo "update_needed=false" >> $GITHUB_OUTPUT
          echo "Already on latest version: $LATEST"
        fi

    - name: Trigger build workflow
      if: steps.compare.outputs.update_needed == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
          -d '{
            "ref": "main",
            "inputs": {
              "update_phpcs": "true",
              "phpcs_version": "${{ steps.latest.outputs.version }}",
              "phpcs_url": "${{ steps.latest.outputs.phpcs_url }}",
              "phpcbf_url": "${{ steps.latest.outputs.phpcbf_url }}"
            }
          }'
        
        echo "Triggered build workflow with PHPCS update: ${{ steps.latest.outputs.version }}"